### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by andrewclavin** [TheLuomamr/MySQL#1]
Great work, code looks excellent. Love seeing the lets and consts in there!

Next target: async await and arrow/lambda functions.

I noticed in your code you have a then inside a then and it starts to get pretty hairy from here on in when you have to start really nesting then promises... so instead we are going to try to do async await.

Instead of:
`function(){
    asyncFunctionReturningPromise(arguments).then(
         function(promiseArg){ 
             codeAfterAsyncPromiseResolvesProbablyUsingPromiseArg
         }
    )
}`

We want to do:
`async function(){
    const promiseArg = await asyncFunctionReturningPromise(arguments)
    codeAsyncPromiseReslovesProbablyUsingPromiseArg
}`

the other is the arrow/lambda functions, instead of:
`function(arguments, function(){callbackFunctionStuff})`
we can try:
`function(arguments, () => {callbackFunctionStuff})`

there are some nuances to how the arrow function around the javascript 'this' object and they can be less performant, but it's good to just start getting used to using it and get a feel for how it can replace normal anonymous function definition, in the async await stuff, the outer function i wrote that takes the async prefix you could also make an arrow function by doing `async () => {...}`

**Comment by TheLuomamr** [comment]
I'll try to incorporate the async/lamda. Just forgetful sometimes since we don't use those in class on activities really. But I appreciate the feedback and will continue trucking along.  Thanks.
